name: Supabase CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Login to Supabase
        run: supabase login --token "${{ secrets.SUPABASE_ACCESS_TOKEN }}"

      - name: Link project
        run: supabase link --project-ref "${{ secrets.SUPABASE_PROJECT_REF }}"

      - name: Push migrations (skip if none)
        run: |
          if [ -d supabase/migrations ] && [ "$(ls -A supabase/migrations || true)" ]; then
            supabase db push
          else
            echo "No migrations to push."
          fi
